[package]
name = "gencf"
version = "0.1.0"
edition = "2021"

[dependencies]
gencf_core = { path = "core" }
gencf_macros = { path = "macros" }
gencf_util = { path = "util" }

[workspace]
members = ["macros", "core", "util"]